FROM node:18-alpine

ENV port=8090
COPY . .

RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*

ARG ENVIRONMENT
ARG DATABASE_URL
ARG STRIPE_SECRET_DEMO
ARG STRIPE_WEBHOOK_DEMO
ARG STRIPE_SECRET_LIVE
ARG STRIPE_WEBHOOK_LIVE
ARG BASE_URL
ARG SLACK_WEBHOOK_URL
ARG SUPABASE_KEY
ARG SUPABASE_URL
ARG JWT_SECRET
ARG OPENAI_API_KEY
ARG S3_ENDPOINT
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG TELEGRAM_TOKEN
ARG DISCORD_TOKEN

RUN echo $DATABASE_URL

RUN apk add openssl1.1-compat
RUN yarn
RUN yarn start

EXPOSE 8090
CMD [ "node", "./dist/main.js" ]