FROM node:18-alpine

ENV port=8080
COPY . .

RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*

ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG STRIPE_SECRET_DEMO
ENV STRIPE_SECRET_DEMO=$STRIPE_SECRET_DEMO
ARG STRIPE_WEBHOOK_DEMO
ENV STRIPE_WEBHOOK_DEMO=$STRIPE_WEBHOOK_DEMO
ARG STRIPE_SECRET_LIVE
ENV STRIPE_SECRET_LIVE=$STRIPE_SECRET_LIVE
ARG STRIPE_WEBHOOK_LIVE
ENV STRIPE_WEBHOOK_LIVE=$STRIPE_WEBHOOK_LIVE
ARG BASE_URL
ENV BASE_URL=$BASE_URL
ARG SLACK_WEBHOOK_URL
ENV SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
ARG SUPABASE_KEY
ENV SUPABASE_KEY=$SUPABASE_KEY
ARG SUPABASE_URL
ENV SUPABASE_URL=$SUPABASE_URL
ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET
ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ARG S3_ENDPOINT
ENV S3_ENDPOINT=$S3_ENDPOINT
ARG S3_ACCESS_KEY
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY
ARG S3_SECRET_KEY
ENV S3_SECRET_KEY=$S3_SECRET_KEY
ARG TELEGRAM_TOKEN
ENV TELEGRAM_TOKEN=$TELEGRAM_TOKEN
ARG DISCORD_TOKEN
ENV DISCORD_TOKEN=$DISCORD_TOKEN

RUN echo $DATABASE_URL
RUN echo $SUPABASE_KEY
RUN echo $SUPABASE_URL


RUN apk add openssl1.1-compat
RUN yarn

EXPOSE 8080
CMD [ "yarn", "start" ]